### ISSUE TITLE
Error 404 missing page

### ISSUE THREAD

**Issue by jallwork** [alexa-samples/skill-sample-python-highlowgame#12]
The link to the Voice user interface page is wrong or page is missing.
Reproduce:

Go to this page: https://github.com/alexa/skill-sample-python-highlowgame#readme
Click Getting Started button, or button 1 (Voice user interface)
See Error 404
Trying to access page:

https://github.com/alexa/skill-sample-python-highlowgame/blob/master/instructions/1-voice-user-interface.md

**Comment by jallwork** [comment]
Actually ALL the number button links are missing

**Comment by jallwork** [comment]
And anyway it looks like the High Low Skill  is no longer available as a template

**Comment by aszk** [comment]
@jallwork I have removed the buttons and updated Get Started! link to correct document.
Thank you so much for the feedback.
